# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: blueprint.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import nextx.grpc.protos.blueprint_pb2 as blueprint_pb2


class BlueprintServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetActiveProjectForBU(self, stream: 'grpclib.server.Stream[blueprint_pb2.BusinessUnitActiveBlueprintRequest, blueprint_pb2.BusinessUnitActiveBlueprintResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetBusinessUnitActiveProjects(self, stream: 'grpclib.server.Stream[blueprint_pb2.BusinessUnitBlueprintsRequest, blueprint_pb2.BusinessUnitBlueprintsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/blueprints.BlueprintService/GetActiveProjectForBU': grpclib.const.Handler(
                self.GetActiveProjectForBU,
                grpclib.const.Cardinality.UNARY_UNARY,
                blueprint_pb2.BusinessUnitActiveBlueprintRequest,
                blueprint_pb2.BusinessUnitActiveBlueprintResponse,
            ),
            '/blueprints.BlueprintService/GetBusinessUnitActiveProjects': grpclib.const.Handler(
                self.GetBusinessUnitActiveProjects,
                grpclib.const.Cardinality.UNARY_UNARY,
                blueprint_pb2.BusinessUnitBlueprintsRequest,
                blueprint_pb2.BusinessUnitBlueprintsResponse,
            ),
        }


class BlueprintServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetActiveProjectForBU = grpclib.client.UnaryUnaryMethod(
            channel,
            '/blueprints.BlueprintService/GetActiveProjectForBU',
            blueprint_pb2.BusinessUnitActiveBlueprintRequest,
            blueprint_pb2.BusinessUnitActiveBlueprintResponse,
        )
        self.GetBusinessUnitActiveProjects = grpclib.client.UnaryUnaryMethod(
            channel,
            '/blueprints.BlueprintService/GetBusinessUnitActiveProjects',
            blueprint_pb2.BusinessUnitBlueprintsRequest,
            blueprint_pb2.BusinessUnitBlueprintsResponse,
        )
